All primitives working fine. All components (except MPI specific) work fine Also created a different parser for everyone to generate their throw events header file
git-svn-id: https://svn.mcs.anl.gov/repos/cifts/ftb/trunk@315 b452418e-dd38-0410-89fe-f8a55b138f88

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -119,19 +119,19 @@ elif test "$CLIENTS" == "bgl"; then
 	fi
 fi
 dnl Create throw_events.h file
-dnl PARSER_PATH=`pwd`/utils;
-dnl SCHEMA_FILES_PATH=`pwd`/components/schemas/*.xml;
-dnl echo "Converting throw event schema files"
-dnl for i in `ls $SCHEMA_FILES_PATH`; do
-dnl    temp=$temp"$i ";
-dnl done
-dnl perl $PARSER_PATH/ftb_throwevent_parser.pl $temp
-dnl if test ! -e `pwd`/ftb_throw_events.h; then
-dnl 	echo "ftb_throw_events.h could not be created.";
-dnl 	echo "configure script aborting...correct errors first" >&2;
-dnl 	exit 1;
-dnl fi
-dnl /bin/mv `pwd`/ftb_throw_events.h `pwd`/include/;
+PARSER_PATH=`pwd`/utils;
+SCHEMA_FILES_PATH=`pwd`/components/schemas/*.xml;
+echo "Converting throw event schema files"
+for i in `ls $SCHEMA_FILES_PATH`; do
+   temp=$temp"$i ";
+ done
+perl $PARSER_PATH/ftb_event_parser.pl $temp
+if test ! -e `pwd`/ftb_throw_events.h; then
+	echo "ftb_throw_events.h could not be created.";
+ 	echo "configure script aborting...correct errors first" >&2;
+ 	exit 1;
+fi
+/bin/mv `pwd`/ftb_throw_events.h `pwd`/include/;
 
 dnl Create include/ftb_conf file
 FTB_CONF_FILE=`pwd`/include/ftb_conf.h
