configure.in : Removed AC_INSTALL command, enforced check for presence of ftb_throw_events.h. ./configure now aborts if file is not present
Makefile.in : Removed un-necessary echo statements

autogen.sh : Modified cleanup to remove ftb_throw_events.h



git-svn-id: https://svn.mcs.anl.gov/repos/cifts/projects/cifts/ftb/trunk@297 b452418e-dd38-0410-89fe-f8a55b138f88

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -6,7 +6,6 @@ AC_PREFIX_DEFAULT('/usr/local')
 saveCFLAGS=$CFLAGS
 AC_PROG_CC
 CFLAGS=$saveCFLAGS
-AC_PROG_INSTALL
 AC_PROG_RANLIB
 
 dnl Get bootstrap server name
@@ -127,6 +126,11 @@ for i in `ls $SCHEMA_FILES_PATH`; do
    temp=$temp"$i ";
 done
 perl $PARSER_PATH/ftb_throwevent_parser.pl $temp
+if test ! -e `pwd`/ftb_throw_events.h; then
+	echo "ftb_throw_events.h could not be created.";
+	echo "configure script aborting...correct errors first" >&2;
+	exit 1;
+fi
 /bin/mv `pwd`/ftb_throw_events.h `pwd`/include/;
 
 dnl Create include/ftb_conf file
@@ -206,5 +210,4 @@ AC_OUTPUT(Makefile 								\
 	  src/client_lib/platforms/BGL/zoid_client/server/Makefile		\
 	  src/agent/Makefile							\
 	  components/examples/Makefile)
-#examples/Makefile)
 
