Enable support for BG/P. - The platforms/bgl directory has been renamed to platforms/bg, since support for BGP has been added. - The FTB Watchdog program will now be compiled for BGP. - Note: This commit will break the build, since certain files under platforms/bg have not been renamed. The next commit will fix this.
git-svn-id: https://svn.mcs.anl.gov/repos/cifts/ftb/trunk@474 b452418e-dd38-0410-89fe-f8a55b138f88

diff --git a/components/configure.in b/components/configure.in
--- a/components/configure.in
+++ b/components/configure.in
@@ -20,7 +20,7 @@ dnl	exit 1;
 dnl fi
 
 dnl Expose option for platform type
-AC_ARG_WITH(platform, [  --with-platform=<platform type>        Possible values: bgl, linux],
+AC_ARG_WITH(platform, [  --with-platform=<platform type>        Possible values: bgl, bgp, linux],
 	                          CLIENTS=$withval, CLIENTS=linux)
 AC_MSG_CHECKING(checking platform support)
 AC_MSG_RESULT($CLIENTS)
@@ -28,52 +28,60 @@ AC_MSG_RESULT($CLIENTS)
 FTB_LIB_LINUX_NAME=ftb
 if  test "$CLIENTS" == "linux"; then
 	clients="linux";
-elif test "$CLIENTS" == "bgl"; then
-	clients="bgl linux";
-	unset_var=0;
-	ZOID_CLIENT_DIR='${abs_top_srcdir}/src/client_lib/platforms/bgl/zoid_client';
-	FTB_LIB_BGL_CN_NAME=ftb_blrts
-	if test "$ENVFILE" == ""; then
-		BGL_ENVFILE="bgl_setup_env";
-	else
-		BGL_ENVFILE="$ENVFILE";
+elif [[ "$CLIENTS" == "bgl" ]] || [[ "$CLIENTS" == "bgp" ]]; then
+	if [[ "$CLIENTS" == "bgl" ]]; then
+	    clients="bgl linux";
+	elif [[ "$CLIENTS" == "bgp" ]]; then
+	    clients="bgp linux";
 	fi
-	if test ! -r "$BGL_ENVFILE" ; then
-		echo "error: BGL environment file '$BGL_ENVFILE' does not exist or is not readable";
+	unset_var=0;
+	ZOID_CLIENT_DIR='${abs_top_srcdir}/src/client_lib/platforms/bg/zoid_client';
+	FTB_LIB_BG_CN_NAME=ftb_blrts
+	if [[ -f "$ENVFILE" ]]; then
+		BG_ENVFILE="$ENVFILE";
+	else
+	    if [[ "$CLIENTS" == "bgl" ]]; then
+		BG_ENVFILE="../bgl_setup_env";
+	    elif [[ "$CLIENTS" == "bgp" ]]; then
+		BG_ENVFILE="../bgp_setup_env";
+	    fi
+	fi
+	if test ! -r "$BG_ENVFILE" ; then
+		echo "error: BG environment file '$BG_ENVFILE' does not exist or is not readable";
 		echo "configure script aborting...correct errors first"
 		exit 1;
 	else
-		source $BGL_ENVFILE;
+		source $BG_ENVFILE;
 	fi
 	if test -z "$ZOID_HOME"; then
 		unset_var=1;
-		echo "error: Required environment variable not set: ZOID_HOME. Please check BGL environment variables file." >&2;
+		echo "error: Required environment variable not set: ZOID_HOME. Please check BG environment variables file." >&2;
 	else
 		ZOID_HOME="export ZOID_HOME=$ZOID_HOME";
 	fi
 	if test -z "$ZOID_LIBC_PATH"; then
 		unset_var=1;
-		echo "error: Required environment variable not set: ZOID_LIBC_PATH. Please check BGL environment variables file." >&2;
+		echo "error: Required environment variable not set: ZOID_LIBC_PATH. Please check BG environment variables file." >&2;
 	else
 		ZOID_LIBC_PATH="export ZOID_LIBC_PATH=$ZOID_LIBC_PATH";
 	fi
 	if test -z "$CC_BLRTS"; then
 		unset_var=1;
-		echo "error: Required enviroment variable not ste: CC_BLRTS. Please check BGL environment variables file.";
+		echo "error: Required enviroment variable not ste: CC_BLRTS. Please check BG environment variables file.";
 	else
 		CC_BLRTS="export CC_BLRTS=$CC_BLRTS";
 	fi
 	if test -z "$AR_BLRTS"; then
 		unset_var=1;
-		echo "error: Required enviroment variable not ste: AR_BLRTS. Please check BGL environment variables file.";
+		echo "error: Required enviroment variable not ste: AR_BLRTS. Please check BG environment variables file.";
 	else
 		AR_BLRTS="export AR_BLRTS=$AR_BLRTS";
 	fi
-	if test -z "$BGLSYS_LIB_PATH"; then
+	if test -z "$BGSYS_LIB_PATH"; then
 		unset_var=1;
-		echo "error: Required environment variable not set: BGLSYS_LIB_PATH. Please check BGL environment variables file." >&2;
+		echo "error: Required environment variable not set: BGSYS_LIB_PATH. Please check BG environment variables file." >&2;
 	else
-		BGLSYS_LIB_PATH="export BGLSYS_LIB_PATH=$BGLSYS_LIB_PATH";
+		BGSYS_LIB_PATH="export BGSYS_LIB_PATH=$BGSYS_LIB_PATH";
 	fi
 	if test $unset_var == 1; then
 		echo "configure script aborting...correct errors first" >&2;
@@ -92,7 +100,7 @@ AC_SUBST(ZOID_HOME)
 AC_SUBST(ZOID_LIBC_PATH)
 AC_SUBST(CC_BLRTS)
 AC_SUBST(AR_BLRTS)
-AC_SUBST(BGLSYS_LIB_PATH)
+AC_SUBST(BGSYS_LIB_PATH)
 AC_SUBST(clients)
 AC_SUBST(ZOID_CLIENT_DIR)
 AC_SUBST(FTB_HOME)
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -11,9 +11,9 @@ CFLAGS=$saveCFLAGS
 AC_PROG_RANLIB
 
 dnl Get bootstrap server name
-AC_ARG_WITH(bstrap-server, [  --with-bstrap-server=<hostname>       Hostname of Bootstrapping server[no default]],
+AC_ARG_WITH(bstrap-server, [  --with-bstrap-server=<IP Address>     IP Address of Bootstrapping server <no default>],
 	                 FTB_BSTRAP_SERVER=$withval, FTB_BSTRAP_SERVER='')
-AC_MSG_CHECKING(checking bootstrap server name)
+AC_MSG_CHECKING(checking bootstrap server IP Address)
 AC_MSG_RESULT($FTB_BSTRAP_SERVER)
 if test "$FTB_BSTRAP_SERVER" == ""; then
 	echo "Bootstrap server host name needed. You can also override it via an environment variable leter";
@@ -24,14 +24,14 @@ AC_DEFINE_UNQUOTED(FTB_BSTRAP_SERVER, "${FTB_BSTRAP_SERVER}", [Hostname for the 
 
 
 dnl Get bootstrap server port number
-AC_ARG_WITH(bstrap-port, [  --with-bstrap-port=<port number>	Port number of Bootstrapping server[14455]],
+AC_ARG_WITH(bstrap-port, [  --with-bstrap-port=<port number>	Port number of Bootstrapping server <14455>],
 	                 FTB_BSTRAP_PORT=$withval, FTB_BSTRAP_PORT=14455)
 AC_MSG_CHECKING(checking bootstrap server port number)
 AC_MSG_RESULT($FTB_BSTRAP_PORT)
 AC_DEFINE_UNQUOTED(FTB_BSTRAP_PORT, ${FTB_BSTRAP_PORT}, [Port number for the FTB bootstrap server])
 
 dnl Get agent port number
-AC_ARG_WITH(agent-port, [  --with-agent-port=<port number>	Port number on which agent is running[10809]],
+AC_ARG_WITH(agent-port, [  --with-agent-port=<port number>	Port number on which agent is running <10809>],
 			FTB_AGENT_PORT=$withval, FTB_AGENT_PORT=10809)
 AC_MSG_CHECKING(checking agent port number)
 AC_MSG_RESULT($FTB_AGENT_PORT)
@@ -39,88 +39,99 @@ AC_DEFINE_UNQUOTED(FTB_AGENT_PORT, ${FTB_AGENT_PORT}, [FTB Agent port])
 
 
 dnl Expose option for platform type
-AC_ARG_WITH(platform, [  --with-platform=<platform type>	Possible values: bgl, linux],
+AC_ARG_WITH(platform, [  --with-platform=<platform type>	Possible values: bgl, bgp, linux],
  		      CLIENTS=$withval, CLIENTS=linux)
 AC_MSG_CHECKING(checking platform support)
 AC_MSG_RESULT($CLIENTS)
 
 dnl Expose option for BGL enviroment file
-AC_ARG_WITH(platform-envfile, [  --with-platform-envfile=<bgl envfile> Default file will be bgl_setup_env for
-					bgl platforms. For all other platforms,
-					this file is ignored.],
+AC_ARG_WITH(platform-envfile, [  --with-platform-envfile=<bg envfile>	Default file will be
+					    bgl_setup_env for bgl platforms, and
+					    bgp_setup_env for bgp platforms.
+					For all other platforms, this file is ignored.],
 			ENVFILE=$withval, ENVFILE=)
 AC_MSG_CHECKING(user specified platform environment file)
 AC_MSG_RESULT($ENVFILE)
 
 AC_ARG_ENABLE(debug, [  --enable-debug: To enable debug messages. Default is no debug], FTB_DEBUG=$enableval, FTB_DEBUG=no)
-AC_MSG_CHECKING(debug messages)
+AC_MSG_CHECKING(debug log directory)
 AC_MSG_RESULT($FTB_DEBUG)
-if test "$FTB_DEBUG" = "yes" ; then
+if [[ "$FTB_DEBUG" != "no" ]]; then
    AC_DEFINE(FTB_DEBUG,, [FTB Debug definition])
+   AC_DEFINE_UNQUOTED(FTB_LOGDIR,"${FTB_DEBUG}", [FTB Log Directory])
 fi
 
 
 FTB_LIB_LINUX_NAME=ftb
 if  test "$CLIENTS" == "linux"; then
 	clients="linux";
-elif test "$CLIENTS" == "bgl"; then
-	clients="bgl linux";
+elif [[ "$CLIENTS" == "bgl" ]] || [[ "$CLIENTS" == "bgp" ]]; then
+	clients="bg linux";
 	unset_var=0;
-	ZOID_CLIENT_DIR='${abs_top_srcdir}/src/client_lib/platforms/bgl/zoid_client';
-	FTB_LIB_BGL_CN_NAME=ftb_blrts
+	ZOID_CLIENT_DIR='${abs_top_srcdir}/src/client_lib/platforms/bg/zoid_client';
+	FTB_LIB_BG_CN_NAME=ftb_blrts
 	if test "$ENVFILE" == ""; then
-		BGL_ENVFILE="bgl_setup_env";
+	    if [[ "$CLIENTS" == "bgl" ]]; then
+		BG_ENVFILE="bgl_setup_env";
+	    elif [[ "$CLIENTS" == "bgp" ]]; then
+		BG_ENVFILE="bgp_setup_env";
+	    fi
 	else
-		BGL_ENVFILE="$ENVFILE";
+		BG_ENVFILE="$ENVFILE";
 	fi
-	if test ! -r "$BGL_ENVFILE" ; then
-		echo "error: BGL environment file '$BGL_ENVFILE' does not exist or is not readable";
+	if test ! -r "$BG_ENVFILE" ; then
+		echo "error: BG environment file '$BG_ENVFILE' does not exist or is not readable";
 		echo "configure script aborting...correct errors first"
 		exit 1;
 	else
-		source $BGL_ENVFILE;
+		source $BG_ENVFILE;
+	fi
+	if [[ "$CLIENTS" == "bgl" ]]; then
+		PLATFORM="bgl";
+	elif [[ "$CLIENTS" == "bgp" ]]; then
+		PLATFORM="bgp";
 	fi
 	if test -z "$ZOID_HOME"; then
 		unset_var=1;
-		echo "error: Required environment variable not set: ZOID_HOME. Please check BGL environment variables file." >&2;
+		echo "error: Required environment variable not set: ZOID_HOME. Please check BG environment variables file." >&2;
 	else
 		ZOID_HOME="export ZOID_HOME=$ZOID_HOME";
 	fi
 	if test -z "$ZOID_LIBC_PATH"; then
 		unset_var=1;
-		echo "error: Required environment variable not set: ZOID_LIBC_PATH. Please check BGL environment variables file." >&2;
+		echo "error: Required environment variable not set: ZOID_LIBC_PATH. Please check BG environment variables file." >&2;
 	else
 		ZOID_LIBC_PATH="export ZOID_LIBC_PATH=$ZOID_LIBC_PATH";
 	fi
 	if test -z "$BLRTS_PATH"; then
 		unset_var=1;
-		echo "error: Required environment variable not set: BLRTS_PATH. Please check BGL environment variables file." >&2;
+		echo "error: Required environment variable not set: BLRTS_PATH. Please check BG environment variables file." >&2;
 	else
 		BLRTS_PATH="export BLRTS_PATH=$BLRTS_PATH";
 	fi
 	if test -z "$CC_BLRTS"; then
 		unset_var=1;
-		echo "error: Required enviroment variable not ste: CC_BLRTS. Please check BGL environment variables file.";
+		echo "error: Required enviroment variable not ste: CC_BLRTS. Please check BG environment variables file.";
 	else
 		CC_BLRTS="export CC_BLRTS=$CC_BLRTS";
 	fi
 	if test -z "$AR_BLRTS"; then
 		unset_var=1;
-		echo "error: Required enviroment variable not ste: AR_BLRTS. Please check BGL environment variables file.";
+		echo "error: Required enviroment variable not ste: AR_BLRTS. Please check BG environment variables file.";
 	else
 		AR_BLRTS="export AR_BLRTS=$AR_BLRTS";
 	fi
 	if test -z "$RANLIB_BLRTS"; then
 		unset_var=1;
-		echo "error: Required enviroment variable not ste: RANLIB_BLRTS. Please check BGL environment variables file.";
+		echo "error: Required enviroment variable not ste: RANLIB_BLRTS. Please check BG environment variables file.";
 	else
 		RANLIB_BLRTS="export RANLIB_BLRTS=$RANLIB_BLRTS";
 	fi
-	if test -z "$BGLSYS_LIB_PATH"; then
+	if test -z "$BGSYS_LIB_PATH"; then
 		unset_var=1;
-		echo "error: Required environment variable not set: BGLSYS_LIB_PATH. Please check BGL environment variables file." >&2;
+		echo "error: Required environment variable not set: BGSYS_LIB_PATH. Please check BG environment variables file." >&2;
 	else
-		BGLSYS_LIB_PATH="export BGLSYS_LIB_PATH=$BGLSYS_LIB_PATH";
+		BGSYS_LIB_PATH="export BGSYS_LIB_PATH=$BGSYS_LIB_PATH";
 	fi
 	if test $unset_var == 1; then
 		echo "configure script aborting...correct errors first" >&2;
@@ -157,15 +168,16 @@ AC_SUBST(BLRTS_PATH)
 AC_SUBST(CC_BLRTS)
 AC_SUBST(AR_BLRTS)
 AC_SUBST(RANLIB_BLRTS)
-AC_SUBST(BGLSYS_LIB_PATH)
+AC_SUBST(BGSYS_LIB_PATH)
 AC_SUBST(BGL_ENVFILE)
 AC_SUBST(clients)
+AC_SUBST(PLATFORM)
 AC_SUBST(FTB_NETWORK_CFLAG)
 AC_SUBST(network)
 AC_SUBST(TEMPSBIN)
 AC_SUBST(TEMPLIB)
 AC_SUBST(ZOID_CLIENT_DIR)
-AC_SUBST(FTB_LIB_BGL_CN_NAME)
+AC_SUBST(FTB_LIB_BG_CN_NAME)
 AC_SUBST(FTB_LIB_LINUX_NAME)
 AC_SUBST(FTB_LIB_PATH_SHARED)
 AC_SUBST(FTB_LIB_PATH_STATIC)
@@ -190,10 +202,10 @@ AC_OUTPUT(Makefile 								\
 	  src/client_lib/Makefile 						\
 	  src/client_lib/platforms/Makefile 					\
 	  src/client_lib/platforms/linux/Makefile 				\
-	  src/client_lib/platforms/bgl/Makefile 				\
-	  src/client_lib/platforms/bgl/zoid_client/Makefile 			\
-	  src/client_lib/platforms/bgl/zoid_client/implementation/Makefile	\
-	  src/client_lib/platforms/bgl/zoid_client/client/Makefile		\
-	  src/client_lib/platforms/bgl/zoid_client/server/Makefile		\
+	  src/client_lib/platforms/bg/Makefile 					\
+	  src/client_lib/platforms/bg/zoid_client/Makefile 			\
+	  src/client_lib/platforms/bg/zoid_client/implementation/Makefile	\
+	  src/client_lib/platforms/bg/zoid_client/client/Makefile		\
+	  src/client_lib/platforms/bg/zoid_client/server/Makefile		\
 	  src/agent/Makefile)
 
