Some code update
git-svn-id: https://svn.mcs.anl.gov/repos/cifts/projects/cifts/ftb/trunk@257 b452418e-dd38-0410-89fe-f8a55b138f88

diff --git a/examples/Makefile b/examples/Makefile
--- a/examples/Makefile
+++ b/examples/Makefile
@@ -1,13 +1,44 @@
-all: ftb_watchdog ftb_polling_logger
+all: $(clients)
 
-CFLAGS_LINUX = -Wall -g -L$(FTB_LIB_PATH_SHARED) -I../include
-LIBS_LINUX   = -l$(FTB_LIB_LINUX_NAME) $(LIBS_PTHREAD)
+Linux: ftb_watchdog ftb_polling_logger ftb_simple
+
+BGL: ftb_simple_bgl
+
+CFLAGS_LINUX  = -Wall -g -I$(INC_DIR)
+LDFLAGS_LINUX = -L$(FTB_LIB_PATH_SHARED)
+LIBS_LINUX    = -l$(FTB_LIB_LINUX_NAME) $(LIBS_PTHREAD)
+
+CFLAGS_BGL    = -Wall -g -I$(INC_DIR) -I$(ZOID_HOME)/include -I$(ZOID_CLIENT_DIR)
+LDFLAGS_CN    = -L$(FTB_LIB_PATH_STATIC) -L$(ZOID_LIBC_PATH) -L$(BGLSYS_LIB_PATH)
+LIBS_CN       = -lftb_blrts -lc -lmsglayer.rts -ldevices.rts -lrts.rts -ldevices.rts -lrts.rts
 
 clean:
-	rm -f ftb_watchdog ftb_polling_logger
+	rm -f ftb_watchdog ftb_polling_logger ftb_simple ftb_simple_bgl
+
+ftb_simple_bgl: ftb_simple.c
+	@if [ -z "$(ZOID_HOME)" ]; then \
+        	echo "ZOID_HOME is not set!  Aborting!"; \
+		exit 1; \
+	fi
+	@if [ -z "$(ZOID_LIBC_PATH)" ]; then \
+        	echo "ZOID_LIBC_PATH is not set!  Aborting!"; \
+		exit 1; \
+	fi
+	@if [ -z "$(BLRTS_PATH)" ]; then \
+        	echo "BLRTS_PATH is not set!  Aborting!"; \
+		exit 1; \
+	fi
+	@if [ -z "$(BGLSYS_LIB_PATH)" ]; then \
+		echo "BGLSYS_LIB_PATH is not set!  Aborting!"; \
+		exit 1; \
+	fi
+	$(CC_BLRTS) $(CFLAGS_BGL) $(LDFLAGS_CN) -o $@ $< $(LIBS_CN)
+
+ftb_simple: ftb_simple.c
+	$(CC) $(CFLAGS_LINUX) $(LDFLAGS_LINUX) -o $@ $< $(LIBS_LINUX)
 
 ftb_watchdog: ftb_watchdog.c
-	$(CC) $(CFLAGS_LINUX) -o $@ $< $(LIBS_LINUX)
+	$(CC) $(CFLAGS_LINUX) $(LDFLAGS_LINUX) -o $@ $< $(LIBS_LINUX)
 
 ftb_polling_logger: ftb_polling_logger.c
-	$(CC) $(CFLAGS_LINUX) -o $@ $< $(LIBS_LINUX)
+	$(CC) $(CFLAGS_LINUX) $(LDFLAGS_LINUX) -o $@ $< $(LIBS_LINUX)
diff --git a/src/client_lib/platforms/BGL/Makefile b/src/client_lib/platforms/BGL/Makefile
--- a/src/client_lib/platforms/BGL/Makefile
+++ b/src/client_lib/platforms/BGL/Makefile
@@ -16,6 +16,10 @@ ftb_zoid_client:
 		echo "ZOID_HOME is not set!  Aborting!"; \
 		exit 1; \
 	fi
+	@if [ -z "$(BLRTS_PATH)" ]; then \
+		echo "BLRTS_PATH is not set!  Aborting!"; \
+		exit 1; \
+	fi
 	(cd zoid_client && $(MAKE))
 	
 
